export const defaultState = {
  onePlayerGameType: "",
  multiPlayerGameType: "",
  homePageActive: true,
  gameModeActive: false,
  gameSetupActive: false,
  gameInfoActive: false,
  playerRegActive: false,
  gamePrepActive: false,
  gameGuideActive: false,
  showHome: false,
  showMode: false,
  showSetup: false,
  selectedMode: "",
  numOfPlayer: 0,
  difficulty: "Easy",
  numberToGuess: "",
  newGame: null,
  numOfAttempt: 0,
  numberArray: null,
};
