export const defaultState = {
  isOpenQuit: false,
  isOpenPlayerReg: false,
  homePageActive: true,
  gameModeActive: false,
  gameSetupActive: false,
  gameInfoActive: false,
  playerRegActive: false,
  gamePrepActive: false,
  showHome: false,
  showMode: false,
  showSetup: false,
  selectedMode: '',
  numOfPlayer: 0,
  difficulty: 'Easy',
  numberToGuess: '',
  newGame: null,
};
