export const defaultState = {
  onePlayerGameType: "",
  multiPlayerGameType: "",
  homePageActive: true,
  gameModeActive: false,
  gameSetupActive: false,
  gameInfoActive: false,
  playerRegActive: false,
  gamePrepActive: false,
  gameGuideActive: false,
  showScoreTable: false,
  showHome: false,
  showMode: false,
  showSetup: false,
  showOtherTabs: false,
  selectedMode: "",
  triggeredByTab: false,
  numOfPlayer: 1,
  difficulty: "Easy",
  numberToGuess: "",
  newGame: null,
  numOfAttempt: 0,
  numberArray: null,
  numOfGamesInSession: 0,
  sessionCount: 1,
  counter: 1,
};
